### PR TITLE
update for 0.11

### PR DESCRIPTION
**Pull request by Gerstacker**
Hi, this builds and passes "pulp test" for me. I hope the unsafePartial is ok.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Looks great, thanks! Are you using this library, incidentally?

**Comment by hdgarrood** [comment]
Oops, actually this is wrong, as quaternions don't form a commutative ring. I'll make some changes and release as v2.0.0.

**Comment by Gerstacker** [comment]
Oh, you're right, sorry for the oversight.
I'm moving towards rigid body kinematics using dual quaternions. I haven't
decided yet between quaternion-of-duals and dual-of-quaternions.

**Comment by hdgarrood** [comment]
Ah, interesting! I'm quite pleased to hear people are using this library at all, to be honest, I wasn't expecting it to see much use!

Don't worry about it, I think there's a good chance my code was wrong to start with and you just updated it in the obvious way. :)

**Pull request merged**
